resources:
  - name: prov_repo
    type: gitRepo
    integration: "qhode_gh"
    pointer:
      sourceName: "Qhode/provision"
      branch: master

  # Terraform State for Kermit
  - name: kermit_saas_state
    type: state

  # PEM key for AWS RC account
  - name: kermit_aws_pem
    type: integration
    integration: aws-rc-pem

  # CREDS for AWS RC account
  - name: kermit_aws_key
    type: integration
    integration: aws_rc_access

jobs:
  - name: kermit_prov
    type: runSh
    steps:
      - IN: kermit_aws_pem
        switch: off
      - IN: kermit_aws_key
        switch: off
      - IN: kermit_saas_state
        switch: off
      - IN: prov_repo
        switch: off
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "prov_repo")
            - ./provision.sh kermit saas
      - OUT: kermit_saas_state
    on_success:
      script:
        - shipctl put_resource_state_multi kermit_saas_state "nat_priv_ip=$(terraform output inst_nat_kermit_priv_ip)" "nat_pub_ip=$(terraform output inst_nat_kermit_pub_ip)"
        - shipctl put_resource_state_multi kermit_saas_state "onebox_priv_ip=$(terraform output inst_onebox_kermit_priv_ip)"
    on_failure:
      - script: echo 'FAILURE!'
    always:
      script:
        - ./archiveProvisionState.sh kermit saas
        - popd
